language: node_js
branches:
  only:
    - master
matrix:
  include:
    # Unit tests on Node Stable
    - node_js: 7
      env:
        global:
          - SAUCE_USERNAME=mdc-web
      addons:
        sauce_connect: true
        jwt:
          secure: EkqjJU3syQ0UsgxGtzs6OZelr0UcK7NfO0HBNuB8BBKUgSibt3Qwr622Kx1RmuT0bmqQYVgO5MsCmUWF16n7WOkJGbgi3We6r7nJSHc3U/V0hhwFs1x5cVk9RFRezMcS5jaQMvUdy/FXIT1YrN5TbTVLTLGHDlx83fd8p7D6TJfCoL1b39h67xXfs3lZSpaJADSr+FCqp7yxLyRjCHfgVIu7Um8E844oT9Z2wKjBOc3aoA8LpdBEcKarIwpY4aMY5ulsH5jNx4YD/G/7Of3wTl1Fqo+bdJYAbXiKBME/jrkfHcR23yuupGAyAgM7uC6pWojYkEMpWcqnzx94CANY/1QuBdkspQPfeEeRxqrz11zfED9nfYtXtW1TwN4Mx9pFcmH6A1pZ/Juu8g08XALAUygeqAiX3QYgTDSYnV6BmYlLa2I0iSMJYjbx3PrdpQxq241+3FA7DRHgxcZztOX8uLLOk62pwWa2A2ipM1FqS7xw+8TpdVksfLe22JVLrC+bIFUTJp4HrjvE1g49hPJi6GXWvYqyMf9EtwJzag6hs+SnquzxEYSdUocxJpjyQpy64x+wll1HQstf5kgy84l9cDK+7X9WXBTrfptASSn3CadokxAQVtynkWe8Wgbi/NXKtXebp/Cp1w7SaLRQgPn+j32j98WnTr9sRzvz9bIkL8M=
      script: npm run pretest && npm run test:unit && npm run posttest
      after_success:
        - codecov
    # Unit tests on LTS
    - node_js: --lts # LTS: See https://github.com/creationix/nvm/pull/1070
      env:
        global:
          - SAUCE_USERNAME=mdc-web
      addons:
        sauce_connect: true
        jwt:
          secure: EkqjJU3syQ0UsgxGtzs6OZelr0UcK7NfO0HBNuB8BBKUgSibt3Qwr622Kx1RmuT0bmqQYVgO5MsCmUWF16n7WOkJGbgi3We6r7nJSHc3U/V0hhwFs1x5cVk9RFRezMcS5jaQMvUdy/FXIT1YrN5TbTVLTLGHDlx83fd8p7D6TJfCoL1b39h67xXfs3lZSpaJADSr+FCqp7yxLyRjCHfgVIu7Um8E844oT9Z2wKjBOc3aoA8LpdBEcKarIwpY4aMY5ulsH5jNx4YD/G/7Of3wTl1Fqo+bdJYAbXiKBME/jrkfHcR23yuupGAyAgM7uC6pWojYkEMpWcqnzx94CANY/1QuBdkspQPfeEeRxqrz11zfED9nfYtXtW1TwN4Mx9pFcmH6A1pZ/Juu8g08XALAUygeqAiX3QYgTDSYnV6BmYlLa2I0iSMJYjbx3PrdpQxq241+3FA7DRHgxcZztOX8uLLOk62pwWa2A2ipM1FqS7xw+8TpdVksfLe22JVLrC+bIFUTJp4HrjvE1g49hPJi6GXWvYqyMf9EtwJzag6hs+SnquzxEYSdUocxJpjyQpy64x+wll1HQstf5kgy84l9cDK+7X9WXBTrfptASSn3CadokxAQVtynkWe8Wgbi/NXKtXebp/Cp1w7SaLRQgPn+j32j98WnTr9sRzvz9bIkL8M=
      script: npm run pretest && npm run test:unit && npm run posttest
    # Closure compiler type checking. Note that TravisCI has Java 7 enabled by default which should
    # work for using closure.
    - node_js: node
      # Make more clear that this job is for running closure tests
      env:
        - CLOSURE=1
      script: npm run test:closure
