language: node_js
branches:
  only:
  - master
matrix:
  include:
  - node_js: 8
    env:
    - TEST_SUITE=lint
    script: npm run lint
  - node_js: 8
    env:
    - TEST_SUITE=unit
    addons:
      sauce_connect: true
    script: npm run test:unit && npm run posttest
    after_success:
    - codecov
  - node_js: 8
    env:
    - TEST_SUITE=closure
    - CLOSURE=1
    script: npm run test:closure
  - node_js: 8
    env:
    - TEST_SUITE=site-generator
    script: npm run test:site
  - node_js: 8
    env:
    - TEST_SUITE=screenshot
    script: npm run screenshot:test
before_install:
  - if [ "$TEST_SUITE" == 'screenshot' ]; then
       if [ ! -d ${HOME}/google-cloud-sdk ]; then
         curl -o /tmp/gcp-sdk.bash https://sdk.cloud.google.com;
         chmod +x /tmp/gcp-sdk.bash;
         /tmp/gcp-sdk.bash --disable-prompts;
       fi;
       export PATH=$PATH:${HOME}/google-cloud-sdk/bin;
       export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
       openssl aes-256-cbc -K $encrypted_2fd1810d2cb7_key -iv $encrypted_2fd1810d2cb7_iv -in travis-gcs.tar.gz.enc -out travis-gcs.tar.gz -d;
       tar -xzf travis-gcs.tar.gz;
       gcloud -q auth activate-service-account --key-file travis-gcs.json;
       gcloud -q config set project material-components-web;
       gcloud -q components install gsutil;
       curl -o /tmp/gsutil.tar.gz https://storage.googleapis.com/pub/gsutil.tar.gz;
       tar xfz /tmp/gsutil.tar.gz -C $HOME
       export PATH=${PATH}:$HOME/gsutil
    fi
