language: node_js
branches:
  # Only run Travis on:
  #   A) Commits made directly to the `master` branch (i.e., merged PRs); and
  #   B) PRs that will eventually be merged into `master`.
  # This prevents excessive resource usage and CI slowness.
  only:
  - master
  - chore/infra/skip-unnecessary-tests
matrix:
  include:
  - node_js: 8
    env:
    - TEST_SUITE=lint
    script:
    - 'if [[ "$SKIP_TESTS" != 1 ]]; then npm run lint; fi'
    - log_untestable_files
  - node_js: 8
    env:
    - TEST_SUITE=unit
    addons:
      sauce_connect: true
    script:
    - 'if [[ "$SKIP_TESTS" != 1 ]]; then npm run test:unit && npm run posttest; fi'
    - log_untestable_files
    after_success:
    - codecov
  - node_js: 8
    env:
    - TEST_SUITE=closure
    - CLOSURE=1
    script:
    - 'if [[ "$SKIP_TESTS" != 1 ]]; then npm run test:closure; fi'
    - log_untestable_files
  - node_js: 8
    env:
    - TEST_SUITE=site-generator
    script:
    - 'if [[ "$SKIP_TESTS" != 1 ]]; then npm run test:site; fi'
    - log_untestable_files
  - node_js: 8
    env:
    - TEST_SUITE=screenshot
    git:
      depth: 200
    script:
    - npm run screenshot:test
    before_install:
    # Source the scripts to export their env vars. See https://superuser.com/a/176788/62792
    - source scripts/travis-testable-env-vars.sh
    - source test/screenshot/infra/commands/travis.sh
    install:
    - npm install
    #- npm ls # Noisy output, but useful for debugging npm package dependency version issues
before_install:
# Source the scripts to export their env vars. See https://superuser.com/a/176788/62792
- source scripts/skip-unnecessary-travis-tests.sh
install:
- 'if [[ "$SKIP_TESTS" != 1 ]]; then npm install; fi'
#- npm ls # Noisy output, but useful for debugging npm package dependency version issues
